### ISSUE TITLE
Cannot alter table

### ISSUE THREAD

**Issue by telvin** [CloudBoost/dashboard#14]
Each time I add or delete a existing column, it just throws following errors

```
Error: Request failed with status code 500
    at createError (https://cloudboost.io/js-sdk/cloudboost.js:7881:16)
    at settle (https://cloudboost.io/js-sdk/cloudboost.js:7853:13)
    at XMLHttpRequest.handleLoad (https://cloudboost.io/js-sdk/cloudboost.js:7741:8)
From previous event:
    at new Promise (https://cloudboost.io/js-sdk/cloudboost.js:196:28)
    at CloudBoost._CB2.default._request (https://cloudboost.io/js-sdk/cloudboost.js:6362:16)
    at CloudTable.save (https://cloudboost.io/js-sdk/cloudboost.js:15960:27)
    at e.value (https://tables.cloudboost.io/index.min.js:36:14363)
    at t.value (https://tables.cloudboost.io/index.min.js:34:8524)
    at Object.o (https://tables.cloudboost.io/index.min.js:2:5536)
    at a (https://tables.cloudboost.io/index.min.js:2:3844)
    at Object.s [as executeDispatchesInOrder] (https://tables.cloudboost.io/index.min.js:2:4059)
    at d (https://tables.cloudboost.io/index.min.js:2:540)
    at f (https://tables.cloudboost.io/index.min.js:2:666)
    at Array.forEach (native)
    at n (https://tables.cloudboost.io/index.min.js:2:6013)
    at Object.processEventQueue (https://tables.cloudboost.io/index.min.js:2:1654)
    at o (https://tables.cloudboost.io/index.min.js:3:17638)
    at Object.handleTopLevel [as _handleTopLevel] (https://tables.cloudboost.io/index.min.js:3:17739)
    at i (https://tables.cloudboost.io/index.min.js:4:14791)
    at o.perform (https://tables.cloudboost.io/index.min.js:2:17116)
    at Object.batchedUpdates (https://tables.cloudboost.io/index.min.js:4:14340)
    at Object.i [as batchedUpdates] (https://tables.cloudboost.io/index.min.js:2:11742)
```

This issue happens on both dashboard and javascript SDK, and just on the existing tables. If I create new tables and begin to alter them, everything is OK.  It seems the issue happens on old tables only

**Comment by nawazdhandala** [comment]
Fixed.
